### ISSUE TITLE
Refactor source code

### ISSUE THREAD

**Issue by arivera12** [sigaloid/LibreTranslate.Net#3]
- [x] Separate class and enums in separate files
- [x] Downgrade net version to its minimum requirement version
- [x] Comment source code for intellisense 
- [ ] Test api
  - [x] Supported Languages
  - [ ] Translate

**Comment by arivera12** [comment]
@sigaloid did you ever make this work properly? 

I am getting 403 atm. 

I used http client instead, then tried out with webclient and same result with both clients...

I created my own branch for this

https://github.com/sigaloid/LibreTranslate.Net/tree/Development-arivera12

**Comment by arivera12** [comment]
I run the project as-is. It seems that maybe we need the api key?
![image](https://user-images.githubusercontent.com/5600102/120431324-55d3c100-c346-11eb-8df9-5aeda9769400.png)

**Comment by arivera12** [comment]
I will try downloading the other project and create my own local server and then try again.

**Comment by arivera12** [comment]
I got able to pull supported cultures but the translate method needs the api key.
![image](https://user-images.githubusercontent.com/5600102/120432263-ad266100-c347-11eb-81a4-25fcd26acf1b.png)

**Comment by sigaloid** [comment]
A specific header needs to be added to the web request in order for this library to act as though it is in the web browser. However, this is bypassing the restrictions the server administrator added (evidently the server load justified the need to lock down the API). In addition, there are still heavy rate limits (see below).

For now, we can add the `api_key` to the constructor 
![image](https://user-images.githubusercontent.com/69441971/120472388-5d6e8680-c395-11eb-99d6-90d88f4884b6.png); this was on my to-do list anyway. This way, legitimate users to the main server with a valid API key can make their requests. 

See these github issues: https://github.com/uav4geo/LibreTranslate/issues/85 https://github.com/uav4geo/LibreTranslate/issues/82

**Comment by arivera12** [comment]
So basically just adding api_key with random value to the request post bypass security?

**Comment by sigaloid** [comment]
No, you need an API key from UAV4GEO in order to use it. However, being on the actual website bypasses this because of the headers sent along. I'm fairly certain @uav4geo does not want libraries or developers bypassing this, so the site could be used by humans and only paying developers would use the API.

**Comment by arivera12** [comment]
Well, in that case we need a temp api key to test it out.

I will be waiting for this then, I have everything almost done, just need to test the translate api.

**Comment by arivera12** [comment]
I created the nuget package, refactored source code, updated readme, just waiting to test the translate method. 

I created the nuget package assuming that we just need to provide the api key to the translate method.

**Comment by sigaloid** [comment]
I believe I can test this out myself since the API functionality is built into libretranslate. Testing soon

**Comment by arivera12** [comment]
Check out my branch

**Comment by sigaloid** [comment]
Well my VPS is out of space and I can't host any more docker containers :disappointed: As long as it matches the specs [here](https://libretranslate.com/docs/) it should work though.

**Comment by arivera12** [comment]
Closing this a moving what is left here: https://github.com/sigaloid/LibreTranslate.Net/issues/7
