### ISSUE TITLE
Remove dependency on Newtonsoft.Json, use System.Text.Json

### ISSUE THREAD

**Issue by sigaloid** [sigaloid/LibreTranslate.Net#6]
Might not be possible due to .net std 1.1, but in case: https://docs.microsoft.com/en-us/dotnet/standard/serialization/system-text-json-how-to?pivots=dotnet-5-0

**Comment by arivera12** [comment]
`System.Text.Json` is on a further version of the net std 1.1 and also throws error serializing one of the models for some reason.

**Comment by sigaloid** [comment]
>System.Text.Json is on a further version of the net std 1.1

Rip.

>also throws error serializing one of the models for some reason

The serialization is different than Newtonsoft.Json, I'd try to resolve it but I like the lower requirements of 1.1. Closing
